import { ArrowRight, ArrowUpRight, Fingerprint, Gamepad2, Gem } from 'lucide-react';
import type { Achievement, Summary, User } from '../types';
import { BadgeArt } from '../components/BadgeArt';
import { number } from '../components/UI';
import { AchievementCard } from './Catalog';

export function Welcome({ onRegister, onLogin }: { onRegister: () => void; onLogin: () => void }) {
  return <><section className="welcome-hero"><div className="hero-copy"><span className="eyebrow">СЕРВИС ИГРОВЫХ ДОСТИЖЕНИЙ</span><h2>Достижения в игре —<br />награды в <em>NFT.</em></h2><p>Сервис получает события от игры, ведёт статистику игрока<br className="desktop-break" /> и выпускает NFT за открытые достижения<br className="desktop-break" /> в блокчейне TON.</p><div className="hero-actions"><button className="button primary" onClick={onRegister}>Зарегистрироваться <ArrowRight size={17} /></button><button className="text-button" onClick={onLogin}>Войти <ArrowUpRight size={15} /></button></div><span className="hero-footnote">Кошелёк нужен только для получения NFT</span></div><div className="hero-art" aria-hidden="true"><div className="folio-grid" /><div className="folio-stamp"><BadgeArt seed="atlas-crystal" large /><span>ДОСТИЖЕНИЕ → NFT</span></div></div></section>
    <section className="how-it-works" aria-labelledby="how-title"><div className="section-heading"><h2 id="how-title">Как это работает</h2><span>Три шага</span></div><div className="steps"><div><span className="step-number">01</span><Gamepad2 size={21} aria-hidden="true" /><h3>Игра передаёт события</h3><p>Матчи, победы, устранения и опыт приходят от игрового сервера.</p></div><div><span className="step-number">02</span><Fingerprint size={21} aria-hidden="true" /><h3>Сервис открывает достижения</h3><p>Когда счётчик достигает порога, достижение открывается автоматически.</p></div><div><span className="step-number">03</span><Gem size={21} aria-hidden="true" /><h3>Игрок получает NFT</h3><p>За открытое достижение сервис выпускает NFT на указанный кошелёк и проверяет его в блокчейне.</p></div></div></section>
  </>;
}

export function Overview({ user, summary, achievements, onCatalog }: { user: User; summary: Summary; achievements: Achievement[]; onCatalog: () => void }) {
  const next = [...achievements].filter(a => !a.unlocked).sort((a, b) => b.progress / b.target - a.progress / a.target).slice(0, 3);
  return <><section className="profile-overview"><div><span className="eyebrow">ИГРОК</span><h2>{user.displayName}</h2><p>Статистика обновляется по событиям игрового сервера. Когда счётчик достигает порога, открывается достижение, и за него можно получить NFT.</p><button className="button primary" onClick={onCatalog}>Открыть каталог <ArrowRight size={17} /></button></div><div className="collection-summary"><BadgeArt seed="personal-atlas" /><div><span className="eyebrow">ДОСТИЖЕНИЯ</span><strong>{number(summary.unlocked)} <span>/ {number(summary.total)}</span></strong><p>достижений открыто</p><button className="text-button" onClick={onCatalog}>NFT выпущено: {number(summary.minted)} <ArrowUpRight size={14} /></button></div></div></section>
    <dl className="summary-row" aria-label="Игровая статистика">{([['Матчи', summary.matches], ['Победы', summary.wins], ['Устранения', summary.kills], ['Опыт, XP', summary.xp]] as const).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{number(value)}</dd></div>)}</dl>
    <section className="next-achievements"><div className="section-heading"><div><h2>{next.length ? 'Ближайшие достижения' : 'Достижения'}</h2></div><button className="text-button" onClick={onCatalog}>Весь каталог <ArrowRight size={16} /></button></div>{next.length ? <div className="achievement-grid">{next.map(a => <AchievementCard key={a.id} achievement={a} />)}</div> : <p className="body-note">{achievements.length ? 'Все достижения открыты. NFT за них можно получить в каталоге.' : 'Достижения появятся после публикации каталога.'}</p>}</section>
  </>;
}
